### ISSUE TITLE
Asterixes are inconsitent

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-webapp#1657]
# On _Children_ page, required Asterixes are way left - they are disappearing into the left margin:

<img width="1280" alt="screen shot 2015-11-24 at 11 01 11" src="https://cloud.githubusercontent.com/assets/191496/11360998/be6601c0-929a-11e5-96b2-d8735c94d3ad.png">

# On _Primary Caregiver 1_ page they're missing

<img width="1280" alt="screen shot 2015-11-24 at 11 02 15" src="https://cloud.githubusercontent.com/assets/191496/11361010/dec0f1be-929a-11e5-9dc6-42da886be2cc.png">

# On _Primary Caregiver 3_ page, one is fine, other is missing

<img width="1280" alt="screen shot 2015-11-24 at 11 02 11" src="https://cloud.githubusercontent.com/assets/191496/11361017/ff71d25c-929a-11e5-926b-12369ea8363d.png">

#

**Comment by alxndrsn** [comment]
Looks like it would be an improvement to modify CSS:

```css
.enketo .required {
  float: left;
  position: relative;
  left: -10px;
  margin-right: -10px;
}
```
